### ISSUE TITLE
Can we use lib using AppCompat as Base Theme

### ISSUE THREAD

**Issue by aarika** [ImaginativeShohag/Why-Not-Image-Carousel#42]
Hello ... Thanks a lot for awesom lib. I have checked several lib but this one is supperb. 

I'm using this library it works fine then I found that if we used `@style/Theme.AppCompat.Light.NoActionBar` then it gives error #15 but if we used `@style/Theme.MaterialComponents.Light.NoActionBar` then we can resolved the issue.

In my case I have several dependency on my project for `AppCompat Theme`. I tried to change it to `MaterialComponents` but it break by app design (mostly happen on `InputTextLayout`).

Can we used this library by using `AppCompat Theme`. If there any work arround I would love to do it, any how I want to use this lib in my project.

Please let me know about it.

Thanks

**Comment by ImaginativeShohag** [comment]
There is no direct workaround to use it with the AppCompat theme.

But you can fork/clone the repo and check out the layout files in the library, and change all material components to defaults one, like instead of `MaterialButton`, use `Button` etc. I don't know finally it will work or not. But you can give it a try.
